### ISSUE TITLE
Crashes when I try running v0.7e

### ISSUE THREAD

**Issue by Vitae666** [Wiedmolol/CQAutomater#7]
It's creating an ExceptionLog.txt file.
Here's what's in it from the 2 times I started it:
4/28/2018 12:47:10 AM
System.NullReferenceException: Object reference not set to an instance of an object.
   at CQFollowerAutoclaimer.AuctionHouse.loadSettings()
   at CQFollowerAutoclaimer.Form1.startTimers()
   at CQFollowerAutoclaimer.Form1..ctor()
   at CQFollowerAutoclaimer.Program.Main()
4/28/2018 12:47:35 AM
System.NullReferenceException: Object reference not set to an instance of an object.
   at CQFollowerAutoclaimer.AuctionHouse.loadSettings()
   at CQFollowerAutoclaimer.Form1.startTimers()
   at CQFollowerAutoclaimer.Form1..ctor()
   at CQFollowerAutoclaimer.Program.Main()

This is the info in the crash details.
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	CQ Auto-follower-claimer-inator
  Problem Signature 02:	0.7.0.0
  Problem Signature 03:	5ae39706
  Problem Signature 04:	CQ Auto-follower-claimer-inator
  Problem Signature 05:	0.7.0.0
  Problem Signature 06:	5ae39706
  Problem Signature 07:	33
  Problem Signature 08:	6
  Problem Signature 09:	System.NullReferenceException
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	0b75
  Additional Information 2:	0b75568a0e6063f8cf7482f4e14934ab
  Additional Information 3:	c0ea
  Additional Information 4:	c0ea3fb5f3ebb5e9eecf94b5491c3827

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\windows\system32\en-US\erofflps.txt

**Comment by Wiedmolol** [comment]
Yup, another version is out. I think I've fixed it.

**Comment by saynotoid** [comment]
the claimer is constantly crashing every single time i try to start it up since to previous update (current is the same)
i can only load it properly without any json settings file, but then it doesn't work and setting file creator helper always crashes the app when i try to save file if it either absent or empty present in the directory. :(:(:(

**Comment by Wiedmolol** [comment]
Are you sure by current you mean 0.7g uploaded ~an hour ago? I know it was crashing on the previous version when you tried to save the setting file but now it should be working.

**Comment by saynotoid** [comment]
just downloaded a minute ago after your previous post hoping for this to be fixed, but it still crashes

btw it hasn't been crashing 2 versions ago while it had for some issue starter

**Comment by Wiedmolol** [comment]
Ok, version 0.7h uploaded. This time it should be totally fixed.

**Comment by saynotoid** [comment]
true, big thx i was able to start it now with my previous settings.json

btw a couple of ... here: there is smth happening to daily chest auto open (it counts timers properly but dont actually open chests - not sure how to reproduce, but it not that annoying (once per 24 hours i can do it manually and the timer in game runs even tho chest wasn't claimed)

and another thing is: the button 'Get Quests' in CQMacroCreator app shows only when i navigate to the quests tab which is annoying, cause usually i press it from the last tab (with PG/rates info panel) followed by - select multiple quests"" button - and now i have to go to 'quests' tab and back which is a waste of time
sorry for putting these here.

**Comment by Wiedmolol** [comment]
Right, I know about daily chest issue. I'm gonna fix it soon.

And about the get quests button, yeah, I was checking if hiding buttons would be good way to get more space without making app's window bigger so I'm gonna change that back. Also you can always change default action on start to '4' and it should download your quests states on start. Quest states are downloaded anyway when you download heroes, they are just not set in app with '3' as default setting.

**Comment by saynotoid** [comment]
thx, btw im totally ok with hiding those buttons for making some space

i just meant those two should be on the same page somehow: 'refresh=get quests' + 'set multiple quests'=(add them as a target) - so that i can push my quests with ease once a week etc if u know what i mean (i usually do this: get quests + set multiple quests + solve + refresh followers + set upper limit to 100% + repeat - a couple of times)

**Comment by Vitae666** [comment]
I agree with Saynotoid.
The usual process with the quests is to go to Other, click Make Multiple button, and Run.
If any solutions happen, click Refresh, Get Quests, Set Upper/Lower, click Make Multiple button and Run. And again as needed.
This way, it's Other, click Make Multiple button, and Run, solutions, Quests, Get Quests,  Other, Refresh, Set Upper/Lower, click Make Multiple button and Run, solutions, Quests....
Just a bit of back and forth.
Solution to that might be to just add the Make Multiple button to the Quests tab. Won't help for the Followers of course. So, really, it's just better to show it on Quests and Other. No reason for the Heroes tab I guess.
